<?php

namespace Database\Seeders;

use App\Models\Plant;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PlantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $plants = [
            [
                'name' => 'Lettuce',
                'scientific_name' => 'Lactuca sativa',
                'description' => 'A leafy green vegetable perfect for beginners. Grows quickly and can be harvested continuously.',
                'category' => 'vegetables',
                'plant_type' => 'annual',
                'days_to_germination' => 7,
                'days_to_harvest' => 45,
                'days_to_maturity' => 60,
                'difficulty_level' => 'beginner',
                'sun_requirement' => 'partial_sun',
                'water_requirement' => 'moderate',
                'min_temperature_c' => 10,
                'max_temperature_c' => 24,
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 7.0,
                'spacing_inches' => 6,
                'depth_inches' => 1,
                'hydroponic_compatible' => true,
                'soil_compatible' => true,
                'aeroponic_compatible' => true,
                'aquaponic_compatible' => true,
                'indoor_compatible' => true,
                'outdoor_compatible' => true,
                'greenhouse_compatible' => true,
                'growing_tips' => 'Keep soil consistently moist. Harvest outer leaves first to allow center to continue growing.',
                'harvesting_tips' => 'Harvest in the morning when leaves are crisp. Cut outer leaves at base.',
                'common_issues' => 'Bolting in hot weather, aphids, slugs.',
                'expected_yield' => '1-2 lbs per plant',
                'nutritional_info' => ['vitamin_k' => 'high', 'vitamin_a' => 'moderate', 'folate' => 'moderate'],
            ],
            [
                'name' => 'Basil',
                'scientific_name' => 'Ocimum basilicum',
                'description' => 'An aromatic herb essential for cooking. Easy to grow and harvest continuously.',
                'category' => 'herbs',
                'plant_type' => 'annual',
                'days_to_germination' => 10,
                'days_to_harvest' => 60,
                'days_to_maturity' => 90,
                'difficulty_level' => 'beginner',
                'sun_requirement' => 'full_sun',
                'water_requirement' => 'moderate',
                'min_temperature_c' => 18,
                'max_temperature_c' => 30,
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 7.5,
                'spacing_inches' => 8,
                'depth_inches' => 1,
                'hydroponic_compatible' => true,
                'soil_compatible' => true,
                'aeroponic_compatible' => true,
                'aquaponic_compatible' => false,
                'indoor_compatible' => true,
                'outdoor_compatible' => true,
                'greenhouse_compatible' => true,
                'growing_tips' => 'Pinch flowers to encourage leaf growth. Harvest regularly to prevent flowering.',
                'harvesting_tips' => 'Harvest leaves in the morning after dew has dried. Pinch just above leaf pairs.',
                'common_issues' => 'Fusarium wilt, aphids, spider mites.',
                'expected_yield' => '0.5-1 lb per plant',
            ],
            [
                'name' => 'Cherry Tomato',
                'scientific_name' => 'Solanum lycopersicum var. cerasiforme',
                'description' => 'Small, sweet tomatoes that are easier to grow than full-size varieties.',
                'category' => 'vegetables',
                'plant_type' => 'annual',
                'days_to_germination' => 14,
                'days_to_harvest' => 75,
                'days_to_maturity' => 120,
                'difficulty_level' => 'intermediate',
                'sun_requirement' => 'full_sun',
                'water_requirement' => 'high',
                'min_temperature_c' => 18,
                'max_temperature_c' => 35,
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 6.8,
                'spacing_inches' => 18,
                'depth_inches' => 2,
                'hydroponic_compatible' => true,
                'soil_compatible' => true,
                'aeroponic_compatible' => false,
                'aquaponic_compatible' => true,
                'indoor_compatible' => true,
                'outdoor_compatible' => true,
                'greenhouse_compatible' => true,
                'growing_tips' => 'Provide support with stakes or cages. Remove suckers for better fruit production.',
                'harvesting_tips' => 'Harvest when fully colored but still firm. Pick regularly to encourage more fruit.',
                'common_issues' => 'Blossom end rot, hornworms, early blight.',
                'expected_yield' => '3-5 lbs per plant',
                'companion_plants' => [2], // Basil
            ],
            [
                'name' => 'Spinach',
                'scientific_name' => 'Spinacia oleracea',
                'description' => 'Nutritious leafy green that thrives in cool weather.',
                'category' => 'vegetables',
                'plant_type' => 'annual',
                'days_to_germination' => 10,
                'days_to_harvest' => 40,
                'days_to_maturity' => 60,
                'difficulty_level' => 'beginner',
                'sun_requirement' => 'partial_shade',
                'water_requirement' => 'moderate',
                'min_temperature_c' => 5,
                'max_temperature_c' => 20,
                'optimal_ph_min' => 6.5,
                'optimal_ph_max' => 7.0,
                'spacing_inches' => 4,
                'depth_inches' => 1,
                'hydroponic_compatible' => true,
                'soil_compatible' => true,
                'aeroponic_compatible' => true,
                'aquaponic_compatible' => true,
                'indoor_compatible' => true,
                'outdoor_compatible' => true,
                'greenhouse_compatible' => true,
                'growing_tips' => 'Plant in cool weather. Succession plant every 2 weeks for continuous harvest.',
                'harvesting_tips' => 'Harvest outer leaves when 3-4 inches long. Cut at base of leaf stem.',
                'common_issues' => 'Bolting in hot weather, downy mildew, aphids.',
                'expected_yield' => '0.5-1 lb per plant',
                'nutritional_info' => ['iron' => 'high', 'vitamin_k' => 'very_high', 'folate' => 'high'],
            ],
            [
                'name' => 'Mint',
                'scientific_name' => 'Mentha',
                'description' => 'Aromatic herb that spreads quickly. Great for teas and cooking.',
                'category' => 'herbs',
                'plant_type' => 'perennial',
                'days_to_germination' => 14,
                'days_to_harvest' => 90,
                'days_to_maturity' => 120,
                'difficulty_level' => 'beginner',
                'sun_requirement' => 'partial_sun',
                'water_requirement' => 'high',
                'min_temperature_c' => 10,
                'max_temperature_c' => 25,
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 7.0,
                'spacing_inches' => 12,
                'depth_inches' => 1,
                'hydroponic_compatible' => true,
                'soil_compatible' => true,
                'aeroponic_compatible' => false,
                'aquaponic_compatible' => true,
                'indoor_compatible' => true,
                'outdoor_compatible' => true,
                'greenhouse_compatible' => true,
                'growing_tips' => 'Contains spread by growing in containers. Pinch flowers to maintain leaf quality.',
                'harvesting_tips' => 'Harvest leaves before flowering for best flavor. Cut stems just above leaf pairs.',
                'common_issues' => 'Invasive spreading, rust, spider mites.',
                'expected_yield' => 'Continuous harvest',
            ],
            [
                'name' => 'Kale',
                'scientific_name' => 'Brassica oleracea var. acephala',
                'description' => 'Hardy leafy green packed with nutrients. Grows well in cool weather.',
                'category' => 'vegetables',
                'plant_type' => 'biennial',
                'days_to_germination' => 7,
                'days_to_harvest' => 55,
                'days_to_maturity' => 75,
                'difficulty_level' => 'beginner',
                'sun_requirement' => 'full_sun',
                'water_requirement' => 'moderate',
                'min_temperature_c' => 5,
                'max_temperature_c' => 25,
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 7.5,
                'spacing_inches' => 12,
                'depth_inches' => 1,
                'hydroponic_compatible' => true,
                'soil_compatible' => true,
                'aeroponic_compatible' => true,
                'aquaponic_compatible' => true,
                'indoor_compatible' => true,
                'outdoor_compatible' => true,
                'greenhouse_compatible' => true,
                'growing_tips' => 'Frost improves flavor. Harvest outer leaves first to allow continued growth.',
                'harvesting_tips' => 'Cut outer leaves at base when 6-8 inches long. Harvest regularly.',
                'common_issues' => 'Cabbage worms, aphids, clubroot.',
                'expected_yield' => '1-2 lbs per plant',
                'nutritional_info' => ['vitamin_k' => 'very_high', 'vitamin_c' => 'very_high', 'vitamin_a' => 'high'],
            ],
        ];

        foreach ($plants as $plantData) {
            Plant::create($plantData);
        }
    }
}
